### ISSUE TITLE
Error messages.

### ISSUE THREAD

**Issue by Biep** [FlowGPT/Cookbook#7]
There should be a comprehensive list of error messages with their meanings and how to get rid of them.
(I currently get **Context length error** - and I have barely started adding knowledge to my character.  No idea where I can change the relevant setting.)

**Comment by AlexXi19** [comment]
Please report bugs through the feedback button on the website! 

![CleanShot 2024-01-25 at 18 59 17@2x](https://github.com/FlowGPT/Cookbook/assets/68758451/5d50f6b4-37a1-4bdb-afc5-bc641b8e891e)
